//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosTutorias
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.AdministracionApp")]
    public partial class ResultadoOperacion : object
    {
        
        private bool ErrorField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Estudiante : object
    {
        
        private ServiciosTutorias.Academico AcademicoField;
        
        private ServiciosTutorias.EstadoEstudiante EstadoEstudianteField;
        
        private ServiciosTutorias.ExperienciasEducativasCursando[] ExperienciasEducativasCursandosField;
        
        private ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicasField;
        
        private ServiciosTutorias.ProblematicaEstudiante[] ProblematicaEstudiantesField;
        
        private ServiciosTutorias.SesionTutoria[] SesionTutoriasField;
        
        private System.Nullable<int> academico_idAcademicoField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoElectronicoField;
        
        private int estado_estudiante_idEstado_estudianteField;
        
        private int idEstudianteField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private System.Nullable<int> semestreCursandoField;
        
        private System.Nullable<long> telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.EstadoEstudiante EstadoEstudiante
        {
            get
            {
                return this.EstadoEstudianteField;
            }
            set
            {
                this.EstadoEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciasEducativasCursando[] ExperienciasEducativasCursandos
        {
            get
            {
                return this.ExperienciasEducativasCursandosField;
            }
            set
            {
                this.ExperienciasEducativasCursandosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicas
        {
            get
            {
                return this.ProblematicaAcademicasField;
            }
            set
            {
                this.ProblematicaAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProblematicaEstudiante[] ProblematicaEstudiantes
        {
            get
            {
                return this.ProblematicaEstudiantesField;
            }
            set
            {
                this.ProblematicaEstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.SesionTutoria[] SesionTutorias
        {
            get
            {
                return this.SesionTutoriasField;
            }
            set
            {
                this.SesionTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> academico_idAcademico
        {
            get
            {
                return this.academico_idAcademicoField;
            }
            set
            {
                this.academico_idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_estudiante_idEstado_estudiante
        {
            get
            {
                return this.estado_estudiante_idEstado_estudianteField;
            }
            set
            {
                this.estado_estudiante_idEstado_estudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> semestreCursando
        {
            get
            {
                return this.semestreCursandoField;
            }
            set
            {
                this.semestreCursandoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Academico", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Academico : object
    {
        
        private ServiciosTutorias.Estudiante[] EstudiantesField;
        
        private ServiciosTutorias.ExperienciaEducativa[] ExperienciaEducativasField;
        
        private ServiciosTutorias.ProgramaEducativo[] ProgramaEducativosField;
        
        private ServiciosTutorias.ReporteTutoria[] ReporteTutoriasField;
        
        private ServiciosTutorias.Rol RolField;
        
        private ServiciosTutorias.Usuario[] UsuariosField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoInstitucionalField;
        
        private int idAcademicoField;
        
        private string nombreField;
        
        private System.Nullable<int> numerPersonalField;
        
        private ServiciosTutorias.ProgramaEducativo[] programa_educativosField;
        
        private int rol_idRolField;
        
        private System.Nullable<long> telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante[] Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciaEducativa[] ExperienciaEducativas
        {
            get
            {
                return this.ExperienciaEducativasField;
            }
            set
            {
                this.ExperienciaEducativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProgramaEducativo[] ProgramaEducativos
        {
            get
            {
                return this.ProgramaEducativosField;
            }
            set
            {
                this.ProgramaEducativosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ReporteTutoria[] ReporteTutorias
        {
            get
            {
                return this.ReporteTutoriasField;
            }
            set
            {
                this.ReporteTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Rol Rol
        {
            get
            {
                return this.RolField;
            }
            set
            {
                this.RolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Usuario[] Usuarios
        {
            get
            {
                return this.UsuariosField;
            }
            set
            {
                this.UsuariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numerPersonal
        {
            get
            {
                return this.numerPersonalField;
            }
            set
            {
                this.numerPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProgramaEducativo[] programa_educativos
        {
            get
            {
                return this.programa_educativosField;
            }
            set
            {
                this.programa_educativosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rol_idRol
        {
            get
            {
                return this.rol_idRolField;
            }
            set
            {
                this.rol_idRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoEstudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class EstadoEstudiante : object
    {
        
        private ServiciosTutorias.Estudiante[] EstudiantesField;
        
        private string estadoField;
        
        private int idEstado_estudianteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante[] Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstado_estudiante
        {
            get
            {
                return this.idEstado_estudianteField;
            }
            set
            {
                this.idEstado_estudianteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciasEducativasCursando", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ExperienciasEducativasCursando : object
    {
        
        private ServiciosTutorias.Estudiante EstudianteField;
        
        private int Estudiante_idEstudianteField;
        
        private ServiciosTutorias.ExperienciaEducativa ExperienciaEducativaField;
        
        private int Experiencia_educativa_idExperiencia_educativaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estudiante_idEstudiante
        {
            get
            {
                return this.Estudiante_idEstudianteField;
            }
            set
            {
                this.Estudiante_idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciaEducativa ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experiencia_educativa_idExperiencia_educativa
        {
            get
            {
                return this.Experiencia_educativa_idExperiencia_educativaField;
            }
            set
            {
                this.Experiencia_educativa_idExperiencia_educativaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicaAcademica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ProblematicaAcademica : object
    {
        
        private ServiciosTutorias.Estudiante EstudianteField;
        
        private int Estudiante_idEstudianteField;
        
        private ServiciosTutorias.ExperienciaEducativa ExperienciaEducativaField;
        
        private int Experiencia_educativa_idExperiencia_educativaField;
        
        private ServiciosTutorias.Problematica ProblematicaField;
        
        private int Problematica_idproblematicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estudiante_idEstudiante
        {
            get
            {
                return this.Estudiante_idEstudianteField;
            }
            set
            {
                this.Estudiante_idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciaEducativa ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experiencia_educativa_idExperiencia_educativa
        {
            get
            {
                return this.Experiencia_educativa_idExperiencia_educativaField;
            }
            set
            {
                this.Experiencia_educativa_idExperiencia_educativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Problematica_idproblematica
        {
            get
            {
                return this.Problematica_idproblematicaField;
            }
            set
            {
                this.Problematica_idproblematicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicaEstudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ProblematicaEstudiante : object
    {
        
        private ServiciosTutorias.Estudiante EstudianteField;
        
        private ServiciosTutorias.Problematica ProblematicaField;
        
        private int estudiante_idEstudianteField;
        
        private int problematica_idproblematicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estudiante_idEstudiante
        {
            get
            {
                return this.estudiante_idEstudianteField;
            }
            set
            {
                this.estudiante_idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int problematica_idproblematica
        {
            get
            {
                return this.problematica_idproblematicaField;
            }
            set
            {
                this.problematica_idproblematicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesionTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class SesionTutoria : object
    {
        
        private ServiciosTutorias.Estudiante EstudianteField;
        
        private ServiciosTutorias.Tutoria TutoriaField;
        
        private int estudiante_idEstudianteField;
        
        private string listaComentariosField;
        
        private int tutoria_idTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Estudiante Estudiante
        {
            get
            {
                return this.EstudianteField;
            }
            set
            {
                this.EstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Tutoria Tutoria
        {
            get
            {
                return this.TutoriaField;
            }
            set
            {
                this.TutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estudiante_idEstudiante
        {
            get
            {
                return this.estudiante_idEstudianteField;
            }
            set
            {
                this.estudiante_idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string listaComentarios
        {
            get
            {
                return this.listaComentariosField;
            }
            set
            {
                this.listaComentariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tutoria_idTutoria
        {
            get
            {
                return this.tutoria_idTutoriaField;
            }
            set
            {
                this.tutoria_idTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Rol : object
    {
        
        private ServiciosTutorias.Academico[] AcademicosField;
        
        private int idRolField;
        
        private string tipoRolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico[] Academicos
        {
            get
            {
                return this.AcademicosField;
            }
            set
            {
                this.AcademicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRol
        {
            get
            {
                return this.idRolField;
            }
            set
            {
                this.idRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoRol
        {
            get
            {
                return this.tipoRolField;
            }
            set
            {
                this.tipoRolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciaEducativa", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ExperienciaEducativa : object
    {
        
        private ServiciosTutorias.Academico AcademicoField;
        
        private ServiciosTutorias.ExperienciasEducativasCursando[] ExperienciasEducativasCursandosField;
        
        private ServiciosTutorias.Materia[] MateriasField;
        
        private ServiciosTutorias.PeriodoEscolar PeriodoEscolarField;
        
        private ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicasField;
        
        private int academico_idAcademicoField;
        
        private int idExperiencia_educativaField;
        
        private string nombreField;
        
        private int periodo_escolar_idPeriodo_escolarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciasEducativasCursando[] ExperienciasEducativasCursandos
        {
            get
            {
                return this.ExperienciasEducativasCursandosField;
            }
            set
            {
                this.ExperienciasEducativasCursandosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Materia[] Materias
        {
            get
            {
                return this.MateriasField;
            }
            set
            {
                this.MateriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.PeriodoEscolar PeriodoEscolar
        {
            get
            {
                return this.PeriodoEscolarField;
            }
            set
            {
                this.PeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicas
        {
            get
            {
                return this.ProblematicaAcademicasField;
            }
            set
            {
                this.ProblematicaAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int academico_idAcademico
        {
            get
            {
                return this.academico_idAcademicoField;
            }
            set
            {
                this.academico_idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExperiencia_educativa
        {
            get
            {
                return this.idExperiencia_educativaField;
            }
            set
            {
                this.idExperiencia_educativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int periodo_escolar_idPeriodo_escolar
        {
            get
            {
                return this.periodo_escolar_idPeriodo_escolarField;
            }
            set
            {
                this.periodo_escolar_idPeriodo_escolarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramaEducativo", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ProgramaEducativo : object
    {
        
        private ServiciosTutorias.Academico Academico1Field;
        
        private ServiciosTutorias.ReporteTutoria[] ReporteTutoriasField;
        
        private ServiciosTutorias.Academico academicoField;
        
        private int coordinadorTutorField;
        
        private int idPrograma_educativoField;
        
        private int jefeCarreraField;
        
        private string modalidadField;
        
        private string nombreField;
        
        private string regionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico Academico1
        {
            get
            {
                return this.Academico1Field;
            }
            set
            {
                this.Academico1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ReporteTutoria[] ReporteTutorias
        {
            get
            {
                return this.ReporteTutoriasField;
            }
            set
            {
                this.ReporteTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int coordinadorTutor
        {
            get
            {
                return this.coordinadorTutorField;
            }
            set
            {
                this.coordinadorTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPrograma_educativo
        {
            get
            {
                return this.idPrograma_educativoField;
            }
            set
            {
                this.idPrograma_educativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jefeCarrera
        {
            get
            {
                return this.jefeCarreraField;
            }
            set
            {
                this.jefeCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modalidad
        {
            get
            {
                return this.modalidadField;
            }
            set
            {
                this.modalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ReporteTutoria : object
    {
        
        private ServiciosTutorias.Academico AcademicoField;
        
        private ServiciosTutorias.Comentario[] ComentariosField;
        
        private ServiciosTutorias.Problematica[] ProblematicasField;
        
        private ServiciosTutorias.ProgramaEducativo ProgramaEducativoField;
        
        private ServiciosTutorias.Tutoria TutoriaField;
        
        private int academico_idAcademicoField;
        
        private string descripcionField;
        
        private int idReporte_TutoriaField;
        
        private int programa_educativo_idPrograma_educativoField;
        
        private int tutoria_idTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Comentario[] Comentarios
        {
            get
            {
                return this.ComentariosField;
            }
            set
            {
                this.ComentariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica[] Problematicas
        {
            get
            {
                return this.ProblematicasField;
            }
            set
            {
                this.ProblematicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProgramaEducativo ProgramaEducativo
        {
            get
            {
                return this.ProgramaEducativoField;
            }
            set
            {
                this.ProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Tutoria Tutoria
        {
            get
            {
                return this.TutoriaField;
            }
            set
            {
                this.TutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int academico_idAcademico
        {
            get
            {
                return this.academico_idAcademicoField;
            }
            set
            {
                this.academico_idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporte_Tutoria
        {
            get
            {
                return this.idReporte_TutoriaField;
            }
            set
            {
                this.idReporte_TutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int programa_educativo_idPrograma_educativo
        {
            get
            {
                return this.programa_educativo_idPrograma_educativoField;
            }
            set
            {
                this.programa_educativo_idPrograma_educativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tutoria_idTutoria
        {
            get
            {
                return this.tutoria_idTutoriaField;
            }
            set
            {
                this.tutoria_idTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Usuario : object
    {
        
        private ServiciosTutorias.Academico AcademicoField;
        
        private int academico_idAcademicoField;
        
        private int idUsuarioField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Academico Academico
        {
            get
            {
                return this.AcademicoField;
            }
            set
            {
                this.AcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int academico_idAcademico
        {
            get
            {
                return this.academico_idAcademicoField;
            }
            set
            {
                this.academico_idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoEscolar", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class PeriodoEscolar : object
    {
        
        private ServiciosTutorias.ExperienciaEducativa[] ExperienciaEducativasField;
        
        private ServiciosTutorias.Tutoria[] TutoriasField;
        
        private System.Nullable<System.DateTime> finPeriodoField;
        
        private int idPeriodo_escolarField;
        
        private System.Nullable<System.DateTime> inicioPeriodoField;
        
        private System.Nullable<System.DateTime> primeraFechaTutoriaField;
        
        private System.Nullable<System.DateTime> segundaFechaTutoriaField;
        
        private System.Nullable<System.DateTime> terceraFechaTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciaEducativa[] ExperienciaEducativas
        {
            get
            {
                return this.ExperienciaEducativasField;
            }
            set
            {
                this.ExperienciaEducativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Tutoria[] Tutorias
        {
            get
            {
                return this.TutoriasField;
            }
            set
            {
                this.TutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> finPeriodo
        {
            get
            {
                return this.finPeriodoField;
            }
            set
            {
                this.finPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodo_escolar
        {
            get
            {
                return this.idPeriodo_escolarField;
            }
            set
            {
                this.idPeriodo_escolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> inicioPeriodo
        {
            get
            {
                return this.inicioPeriodoField;
            }
            set
            {
                this.inicioPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> primeraFechaTutoria
        {
            get
            {
                return this.primeraFechaTutoriaField;
            }
            set
            {
                this.primeraFechaTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> segundaFechaTutoria
        {
            get
            {
                return this.segundaFechaTutoriaField;
            }
            set
            {
                this.segundaFechaTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> terceraFechaTutoria
        {
            get
            {
                return this.terceraFechaTutoriaField;
            }
            set
            {
                this.terceraFechaTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materia", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Materia : object
    {
        
        private ServiciosTutorias.ExperienciaEducativa ExperienciaEducativaField;
        
        private System.Nullable<int> NRCField;
        
        private int experiencia_educativa_idExperiencia_educativaField;
        
        private int idMateriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ExperienciaEducativa ExperienciaEducativa
        {
            get
            {
                return this.ExperienciaEducativaField;
            }
            set
            {
                this.ExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NRC
        {
            get
            {
                return this.NRCField;
            }
            set
            {
                this.NRCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int experiencia_educativa_idExperiencia_educativa
        {
            get
            {
                return this.experiencia_educativa_idExperiencia_educativaField;
            }
            set
            {
                this.experiencia_educativa_idExperiencia_educativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMateria
        {
            get
            {
                return this.idMateriaField;
            }
            set
            {
                this.idMateriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Tutoria : object
    {
        
        private ServiciosTutorias.PeriodoEscolar PeriodoEscolarField;
        
        private ServiciosTutorias.ReporteTutoria[] ReporteTutoriasField;
        
        private ServiciosTutorias.SesionTutoria[] SesionTutoriasField;
        
        private System.Nullable<System.DateTime> fechaEntregaField;
        
        private System.Nullable<System.DateTime> fechaTutoriaField;
        
        private int idTutoriaField;
        
        private System.Nullable<int> numeroTutoriaField;
        
        private int periodo_escolar_idPeriodo_escolarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.PeriodoEscolar PeriodoEscolar
        {
            get
            {
                return this.PeriodoEscolarField;
            }
            set
            {
                this.PeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ReporteTutoria[] ReporteTutorias
        {
            get
            {
                return this.ReporteTutoriasField;
            }
            set
            {
                this.ReporteTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.SesionTutoria[] SesionTutorias
        {
            get
            {
                return this.SesionTutoriasField;
            }
            set
            {
                this.SesionTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaTutoria
        {
            get
            {
                return this.fechaTutoriaField;
            }
            set
            {
                this.fechaTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroTutoria
        {
            get
            {
                return this.numeroTutoriaField;
            }
            set
            {
                this.numeroTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int periodo_escolar_idPeriodo_escolar
        {
            get
            {
                return this.periodo_escolar_idPeriodo_escolarField;
            }
            set
            {
                this.periodo_escolar_idPeriodo_escolarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comentario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Comentario : object
    {
        
        private ServiciosTutorias.ReporteTutoria ReporteTutoriaField;
        
        private string comentariosField;
        
        private int idComentarioField;
        
        private int reporte_Tutoria_idReporte_TutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ReporteTutoria ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios
        {
            get
            {
                return this.comentariosField;
            }
            set
            {
                this.comentariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComentario
        {
            get
            {
                return this.idComentarioField;
            }
            set
            {
                this.idComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reporte_Tutoria_idReporte_Tutoria
        {
            get
            {
                return this.reporte_Tutoria_idReporte_TutoriaField;
            }
            set
            {
                this.reporte_Tutoria_idReporte_TutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Problematica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Problematica : object
    {
        
        private ServiciosTutorias.ClasificacionEstudiante ClasificacionEstudianteField;
        
        private ServiciosTutorias.EstadoProblematica EstadoProblematicaField;
        
        private ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicasField;
        
        private ServiciosTutorias.ProblematicaEstudiante[] ProblematicaEstudiantesField;
        
        private ServiciosTutorias.ReporteTutoria ReporteTutoriaField;
        
        private ServiciosTutorias.Solucion[] SolucionsField;
        
        private int clasificacion_problematica_idClasificacion_problematicaField;
        
        private string descripcionField;
        
        private int estado_problematica_idestado_problematicaField;
        
        private int idproblematicaField;
        
        private int reporte_Tutoria_idReporte_TutoriaField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ClasificacionEstudiante ClasificacionEstudiante
        {
            get
            {
                return this.ClasificacionEstudianteField;
            }
            set
            {
                this.ClasificacionEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.EstadoProblematica EstadoProblematica
        {
            get
            {
                return this.EstadoProblematicaField;
            }
            set
            {
                this.EstadoProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProblematicaAcademica[] ProblematicaAcademicas
        {
            get
            {
                return this.ProblematicaAcademicasField;
            }
            set
            {
                this.ProblematicaAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ProblematicaEstudiante[] ProblematicaEstudiantes
        {
            get
            {
                return this.ProblematicaEstudiantesField;
            }
            set
            {
                this.ProblematicaEstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.ReporteTutoria ReporteTutoria
        {
            get
            {
                return this.ReporteTutoriaField;
            }
            set
            {
                this.ReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Solucion[] Solucions
        {
            get
            {
                return this.SolucionsField;
            }
            set
            {
                this.SolucionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int clasificacion_problematica_idClasificacion_problematica
        {
            get
            {
                return this.clasificacion_problematica_idClasificacion_problematicaField;
            }
            set
            {
                this.clasificacion_problematica_idClasificacion_problematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_problematica_idestado_problematica
        {
            get
            {
                return this.estado_problematica_idestado_problematicaField;
            }
            set
            {
                this.estado_problematica_idestado_problematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idproblematica
        {
            get
            {
                return this.idproblematicaField;
            }
            set
            {
                this.idproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reporte_Tutoria_idReporte_Tutoria
        {
            get
            {
                return this.reporte_Tutoria_idReporte_TutoriaField;
            }
            set
            {
                this.reporte_Tutoria_idReporte_TutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClasificacionEstudiante", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class ClasificacionEstudiante : object
    {
        
        private ServiciosTutorias.Problematica[] ProblematicasField;
        
        private string clasificacionField;
        
        private int idClasificacion_problematicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica[] Problematicas
        {
            get
            {
                return this.ProblematicasField;
            }
            set
            {
                this.ProblematicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clasificacion
        {
            get
            {
                return this.clasificacionField;
            }
            set
            {
                this.clasificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idClasificacion_problematica
        {
            get
            {
                return this.idClasificacion_problematicaField;
            }
            set
            {
                this.idClasificacion_problematicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoProblematica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class EstadoProblematica : object
    {
        
        private ServiciosTutorias.Problematica[] ProblematicasField;
        
        private string estadoField;
        
        private int idestado_problematicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica[] Problematicas
        {
            get
            {
                return this.ProblematicasField;
            }
            set
            {
                this.ProblematicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idestado_problematica
        {
            get
            {
                return this.idestado_problematicaField;
            }
            set
            {
                this.idestado_problematicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solucion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqTutorias.Modelo")]
    public partial class Solucion : object
    {
        
        private ServiciosTutorias.Problematica ProblematicaField;
        
        private string descripcionField;
        
        private int idSolucionField;
        
        private int problematica_idproblematicaField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiciosTutorias.Problematica Problematica
        {
            get
            {
                return this.ProblematicaField;
            }
            set
            {
                this.ProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolucion
        {
            get
            {
                return this.idSolucionField;
            }
            set
            {
                this.idSolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int problematica_idproblematica
        {
            get
            {
                return this.problematica_idproblematicaField;
            }
            set
            {
                this.problematica_idproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosTutorias.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iniciarSesion", ReplyAction="http://tempuri.org/IService1/iniciarSesionResponse")]
        System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> iniciarSesionAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarEstudiante", ReplyAction="http://tempuri.org/IService1/registrarEstudianteResponse")]
        System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarEstudianteAsync(ServiciosTutorias.Estudiante nuevoEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarTutorAcademico", ReplyAction="http://tempuri.org/IService1/registrarTutorAcademicoResponse")]
        System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarTutorAcademicoAsync(ServiciosTutorias.Academico nuevoTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarFechaSesiontutoria", ReplyAction="http://tempuri.org/IService1/registrarFechaSesiontutoriaResponse")]
        System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarFechaSesiontutoriaAsync(ServiciosTutorias.PeriodoEscolar periodoFechas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/asignacionTutorAEstudiante", ReplyAction="http://tempuri.org/IService1/asignacionTutorAEstudianteResponse")]
        System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> asignacionTutorAEstudianteAsync(ServiciosTutorias.Estudiante estudianteAsignacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiciosTutorias.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiciosTutorias.IService1>, ServiciosTutorias.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> iniciarSesionAsync(string username, string password)
        {
            return base.Channel.iniciarSesionAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarEstudianteAsync(ServiciosTutorias.Estudiante nuevoEstudiante)
        {
            return base.Channel.registrarEstudianteAsync(nuevoEstudiante);
        }
        
        public System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarTutorAcademicoAsync(ServiciosTutorias.Academico nuevoTutor)
        {
            return base.Channel.registrarTutorAcademicoAsync(nuevoTutor);
        }
        
        public System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> registrarFechaSesiontutoriaAsync(ServiciosTutorias.PeriodoEscolar periodoFechas)
        {
            return base.Channel.registrarFechaSesiontutoriaAsync(periodoFechas);
        }
        
        public System.Threading.Tasks.Task<ServiciosTutorias.ResultadoOperacion> asignacionTutorAEstudianteAsync(ServiciosTutorias.Estudiante estudianteAsignacion)
        {
            return base.Channel.asignacionTutorAEstudianteAsync(estudianteAsignacion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60669/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
